### ISSUE TITLE
Dendron compatibility: YAML Frontmatter ID

### ISSUE THREAD

**Issue by AsakawaP** [Rudtrack/structured-tree#3]
## How I use this plugin

I take notes with Dendron and Obsidian both to use the great VSCode extensions (e.g. GitLens) and Obsidian plugins (e.g. DataView and Obsidian Git).

And with [Structured Tree](https://github.com/Rudtrack/structured-tree) / [Dendron Tree](https://github.com/levirs565/obsidian-dendron-tree), it is possible to use Obsidian iOS app as a **Dendron app** :-)

## What problem I meet

Both `Structured Tree` and `Dendron Tree` only add dendron-like frontmatter while creating a new note, but can't add frontmatter to existing notes.  
I think there is no other way to add a dendron unique `id` :-(

## What feature I request

- Add a command to generate and insert dendron unique `id` to frontmatter, or [`fixfrontmatter`](https://wiki.dendron.so/notes/ZeC74FYVECsf9bpyngVMU/#fixfrontmatter) for current note.  
  I think it's very helpful! Because the command could be used in QuickAdd macros while creating notes from templates.

- Allow `created` key to use `{{time:x}}`. By default it is `{{date:YYYY-MM-DD}}`.
  This is not necessary because frontmatters can be modified by other plugins.

## One more recommended plugin

For everyone who loves Structured Tree / Dendron Tree, [Front Matter Title](https://github.com/snezhig/obsidian-front-matter-title) is highly recommended. I use this plugin to replace titles in tabs and inline titles :-P

**Comment by Rudtrack** [comment]
Hi! I will look into a quickfix for the date issue! The other request to generate ID for existing notes will most likely take some time to figure out, but I will look into this aswell!

However, keep in mind that this plugin will not necessarily keep compatibility with Dendron in the future. I'm developing this as a standalone alternative so it's possible to use the Dendron way of note-taking in Obsidian since they halted development a while back

I will of course try to keep compatibility , but I cannot garantee it.

**Comment by AsakawaP** [comment]
> Hi! I will look into a quickfix for the date issue! The other request to generate ID for existing notes will most likely take some time to figure out, but I will look into this aswell!
> 
> I will of course try to keep compatibility , but I cannot garantee it.

Thanks for your reply!

I think it's enough if there is a command to generate dendron `id`, since we can use Obsidian templates and plugins to manage YAML frontmatter instead.

For example, use this frontmatter template to create a daily journal:

```yaml
id: REQUESTED_FEATURE
title: {{date}}
desc: '' # default
updated: {{time:x}}
created: {{time:x}}
```

And enable [Linter](https://platers.github.io/obsidian-linter/settings/yaml-rules/#yaml-timestamp) to modify `updated` timestamp automatically.

This new note can be recognized correctly by Dendron! :-P

**Comment by Rudtrack** [comment]
Hi again! In the newest release (1.5.1), you should be able to generate an ID inside existing notes. The command palette has a command to generate the ID inside your current active note.

An option to change `created` to use `{{time:x}}` might arrive later. Would you consider the fact that it's hard coded to use `YYYY-MM-DD` a breaking change for your workflow?

**Comment by AsakawaP** [comment]
Thanks for your work! Here are my review about `1.5.2`:

### Dendron compatibility

It's done!
Now I can use `Structured Tree: Generate ID` command in QuickAdd macros to generate Dendron style notes.
That's what I need! :-)

### Unix Timestamp

[Linter](https://platers.github.io/obsidian-linter/settings/yaml-rules/#yaml-timestamp) is a good friend of Structured Tree :-P
Just disable `Auto-generate Properties` --> `Created Date Property` in `Structured Tree`, and enable `Linter`'s YAML timestamp rules to insert `created: {{time:x}}` and `updated: {{time:x}}` to new notes' frontmatter.
It works fine :-)

… In this way, allow `created` key to use {{time:x}} is not necessary in Structured Tree now.

### One More Request

`Structured Tree: Rename Structured Note` will show a modal with the filename filled in.

Is it possible to fill the current note's filename in `Structured Tree: Lookup Note` modal, just like Dendron? By default it's blank.
I think this will be helpful when you want to create children notes.

**Comment by Rudtrack** [comment]
I think I can create a command for the `Create Note` functionality that already exists when you right click a note in the hierarchy. So it would auto fill with the file name of your current note.

Would you be so kind as to create a new issue for your additonal request? Since it's not directly related to Frontmatter. Always nice to keep things separated 😄

**Comment by AsakawaP** [comment]
Yep, your understand is right :-)
In my *Dendron-style* workflow, `Structured Tree` only manages `id`, `title` and `desc` keys. `created` and `updated` keys are modified by `Linter` after a new note is created.
Now my workflow works fine. I would say that's enough for me 😄 This issue is done.

---

By the way, I think allowing `created` key to use custom configs is still a good idea, e.g. `{{time:YYYY-MM-DD HH:mm:ss}}`.
I use `{{time:x}}` because Dendron will automatically transform Unix timestamp to readable format.
When I created this issue, I had not found Linter's timestamp rules. Maybe you can also recommend others to use Linter instead.
