### ISSUE TITLE
Ideas about Structured Tree

### ISSUE THREAD

**Issue by AsakawaP** [Rudtrack/structured-tree#4]
Here are also some ideas about this plugin:

- enhanced note lookup
  fuzzy search to lookup notes easier
- a command to create notes
  a modal with current file name filled in to create children notes easier
- a command to get brother notes
  surfing in notes sharing the same parent
- `Structured Tree: Rename Structured Note`
  `Refactor Structured Note` or just `Restructure` instead seems better, since this powerful command renames all notes sharing the same prefix.

Maybe you'll have interest 😄

**Comment by Rudtrack** [comment]
A command to create new notes with current file name already filled in is already completed and will arrive with the next update (1.6.0). 

In the same updated I've also changed the name of the rename command to `Structured Tree: Rename Note`. I'll consider changing the name even more later, but I want to keep it as accessible as possible for people that don't use Dendron or are familiar with concepts like refactoring. I'll look into it though!

Estimated release for 1.6.0 is either tonight or tomorrow!

As for fuzzy search and finding brother notes, I'll do some research and look into it!

**Comment by Rudtrack** [comment]
@AsakawaP Fuzzy search is now implemented in the most recent release (1.7.0)
